apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: testing
helmCharts:
- name: pulsar
  includeCRDs: true
  releaseName: pulsar
  version: 3.0.0
  repo: https://pulsar.apache.org/charts